# Generated by Django 4.0.2 on 2022-02-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=20, verbose_name='Genre')),
                ('nationalite', models.CharField(max_length=50, verbose_name='Nationalité')),
                ('paysOrigine', models.CharField(max_length=50, verbose_name="Pays d'origine")),
                ('cin', models.CharField(max_length=15, unique=True, verbose_name='Numéro du CIN')),
                ('datecin', models.DateField(verbose_name='Date de délivrance du CIN')),
                ('lieucin', models.CharField(max_length=50, verbose_name='Lieu de délivrance du CIN')),
                ('numTel', models.CharField(max_length=10, unique=True, verbose_name='Numéro de téléphone')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
                ('picture', models.ImageField(default='media/image_profils/avatar.jpg ', null=True, upload_to='media/image_profils/enseignants', verbose_name='Image de profil')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='suivis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de suivi')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignants')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiants')),
            ],
            options={
                'verbose_name': 'Suivis',
                'verbose_name_plural': 'Suivis',
            },
        ),
        migrations.CreateModel(
            name='responsables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignants')),
                ('parcours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.parcours')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
    ]
