# Generated by Django 4.0.2 on 2022-02-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEtud', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenomEtud', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('dateNaissance', models.DateField(verbose_name='Date de naissance')),
                ('lieuNaissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('sexEtud', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=20, verbose_name='Genre')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('paysOrigine', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('cin', models.CharField(max_length=15, unique=True, verbose_name='Numéro du CIN')),
                ('dateCin', models.DateField(verbose_name='Date de délivrance du CIN')),
                ('lieuCin', models.CharField(max_length=100, verbose_name='Lieu de délivrance du CIN')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('numTel', models.CharField(max_length=10, unique=True, verbose_name='Numéro du téléphone')),
                ('mere', models.CharField(max_length=100, verbose_name='Nom et prénom(s) de la mère')),
                ('pere', models.CharField(max_length=100, null=True, verbose_name='Nom et prénom(s) du père')),
                ('serieBacc', models.CharField(max_length=50, verbose_name='Série du BACC')),
                ('DateBacc', models.DateField(verbose_name="Date d'obtention du BACC")),
                ('LyceeOrigine', models.CharField(max_length=100, verbose_name="Lycée d'origine")),
                ('pictureEtud', models.ImageField(default='static/image/avatar.jpg ', null=True, upload_to='media/image_profils/etudiants', verbose_name='Image de profil')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(choices=[('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030')], max_length=20, verbose_name='Année scolaire')),
                ('classe', models.CharField(choices=[('1ère Année', '1ère Année'), ('2ème Année', '2ème Année'), ('3ème Année', '3ème Année'), ('4ème Année', '4ème Année'), ('5ème Année', '5ème Année')], max_length=20, verbose_name='Classe')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('etablissements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.etablissements')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiants')),
                ('mentions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.mentions')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.parcours')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
            },
        ),
        migrations.CreateModel(
            name='orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcOptimal1', models.CharField(default='none', max_length=100, verbose_name='Choix n° 1')),
                ('pourcentage1', models.FloatField(default=0.0, verbose_name='Pourcentage du choix n° 1')),
                ('parcOptimal2', models.CharField(default='none', max_length=100, verbose_name='Choix n° 2')),
                ('pourcentage2', models.FloatField(default=0.0, verbose_name='Pourcentage du choix n° 2')),
                ('parcOptimal3', models.CharField(default='none', max_length=100, verbose_name='Choix n° 3')),
                ('pourcentage3', models.FloatField(default=0.0, verbose_name='Pourcentage du choix n° 3')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiants')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.niveaux', unique=True)),
            ],
            options={
                'verbose_name': 'Orientation',
                'verbose_name_plural': 'Orientations',
            },
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesTP', models.FloatField(default=0.0, verbose_name='Note du TP')),
                ('notesPartiel', models.FloatField(default=0.0, verbose_name='Note du partiel')),
                ('notesTotal', models.FloatField(default=0.0, verbose_name='Note totale')),
                ('ec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.ec')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiants')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='moyenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(default=0.0, verbose_name='Moyenne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiants')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.niveaux')),
            ],
            options={
                'verbose_name': 'Moyenne',
                'verbose_name_plural': 'Moyennes',
            },
        ),
    ]
